// components/global/user-name.vue
<template>
  <Mfm :text="user.name || user.username" :class="{ premium: user.isPremium }" :plain="true" :nowrap="nowrap" :custom-emojis="user.emojis"/>
</template>

<script lang="ts">
import { defineComponent } from '@nuxtjs/composition-api';

export default defineComponent({
  props: {
    user: {
      type: Object,
      required: true
    },
    nowrap: {
      type: Boolean,
      default: true
    },
  }
});
</script>

// src/components/common/username.tsx
import type { User } from "ayuskey.js/built/entities";
import type { CSSProperties, FC } from "react";
import { MFM } from "../../utils/mfm";

interface Props {
  style?: CSSProperties
  user: User
}

export const UserName: FC<Props> = ({user, style}) => {
  return (
    <MFM text={user.name || user.username} plain={true} emojis={user.emojis} style={style}/>
  )
}
